### ISSUE TITLE
Can't build on centos 5.11

### ISSUE THREAD

**Issue by moi15moi** [annacrombie/muon#268]
I have many build errors when I try to build muon on centos 5.11.
It is probably fine since it has a really really old toolchain, but I believe it would be a good idea to document what is the minimum version of gcc and glibc muon support.

**Comment by kzc** [comment]
muon requires a C99 compiler to build and will work with most posix libc implementations like glibc or musl.

According to the [GCC status page](https://gcc.gnu.org/projects/c-status.html#c99) "C99 is substantially completely supported as of GCC 4.5" which [appears to have been released in 2010](https://gcc.gnu.org/gcc-4.5/).

On the windows side, the latest API or macro to be required appears to be `IO_REPARSE_TAG_APPEXECLINK` which requires Windows 10 from around 2018.

The optional packages git, libarchive, pkgconfig, and curl also have their own compiler requirements and dependencies.

**Comment by moi15moi** [comment]
With debian 7 (which use gcc 4.7.2 and glibc 2.13), I get this error:
```
root@a1356c150845:/home/muon-master# ./bootstrap.sh build
+ dir=build
+ mkdir -p build
+ c99 -Iinclude src/amalgam.c -o build/muon-bootstrap
/tmp/ccojOnYh.o: In function `timer_start':
amalgam.c:(.text+0xcc5eb): undefined reference to `clock_gettime'
/tmp/ccojOnYh.o: In function `timer_read':
amalgam.c:(.text+0xcc639): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
```

This happen because for glibc older then 2.17, we need to use the flags -lrt (see: https://man7.org/linux/man-pages/man3/clock_gettime.3.html)

**Comment by annacrombie** [comment]
Does `LDFLAGS="-lrt" ./bootstrap.sh build` work then?

**Comment by eli-schwartz** [comment]
See also https://github.com/michaelforney/samurai/pull/116

**Comment by moi15moi** [comment]
> Does `LDFLAGS="-lrt" ./bootstrap.sh build` work then?

Yes, it does work, but it is also needed for the setup.
So, in brief, this works:
```bash
LDFLAGS="-lrt" ./bootstrap.sh build
LDFLAGS="-lrt" build/muon-bootstrap setup -Dmeson-docs=disabled build
build/muon-bootstrap -C build samu
build/muon -C build install
```

**Comment by annacrombie** [comment]
@moi15moi does c3eef55354603d538882972fa600b8fe93293cf4 fix this?

**Comment by moi15moi** [comment]
Yes, it does work!

On another note, is it normal that ``docs`` is true even if I passed ``-Dmeson-docs=disabled``? I guess it is normal since ``docs != meson-docs``, but I was wondering because ``docs`` isn't in https://github.com/muon-build/muon/blob/c3eef55354603d538882972fa600b8fe93293cf4/meson_options.txt:
```bash
muon 0.7.0-dev
    platform: posix
    compiler: gcc
    libcurl: false
    libarchive: false
    pkgconfig: 
      null
      exec

    docs: true
setup complete
```

**Comment by annacrombie** [comment]
I've added a new option `docs` which should allow you to completely disable building standalone documentation.  There might be a little confusion since muon also has lots of documentation embedded inside it.  There is currently no way to disable this embedded documentation.
